server:
  port: 8080

spring:
  datasource:
    username: psl_newUser
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/small_green_book?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  data:
    redis:
      host: 192.168.88.130
      port: 6379
      database: 2
      password: 123456
      lettuce:
        pool:
          max-active: 10  #最大连接数
          min-idle: 10    #最小连接数
          max-idle: 0     #空闲最大连接数
          time-between-eviction-runs: 10s #空闲连接检测时间间隔

mybatis:
  configuration:
    #配置mybatis的日志, 指定输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis的驼峰命名自动映射开关 a_column ------> aCloumn
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tHZUXuxNGMrQcWJFZwD
    accessKeySecret: N7oGuFbuy0IuMtJlxPRYER53At4d8N
    bucketName: aminibucket




